// Generated by scripts/sync-deployments.mjs. Do not edit by hand.
export const deployedAddresses = {
  "46630": {
    "agentRegistry": "0x8261CD47Cd22A96Aa169a8381ff5d825797215f3",
    "trackRecord": "0xb1B17711ee5c8737E573156561850DAA9e9799ed",
    "policyModule": "0x3694428E4b527826d168FC7BF3e2e6e26cFE538f",
    "copyVault": "0xf47B9234Ba4aF39Ec28bF3C303B3EDEa3AbE1061",
    "usdg": "0xC9e3E8d3e259Bf33318996AFDe2a5EC134BB3b50"
  },
  "421614": {
    "agentRegistry": "0x8261CD47Cd22A96Aa169a8381ff5d825797215f3",
    "trackRecord": "0xb1B17711ee5c8737E573156561850DAA9e9799ed",
    "policyModule": "0x3694428E4b527826d168FC7BF3e2e6e26cFE538f",
    "copyVault": "0xf47B9234Ba4aF39Ec28bF3C303B3EDEa3AbE1061",
    "usdg": "0xC9e3E8d3e259Bf33318996AFDe2a5EC134BB3b50"
  }
} as const;
